### ISSUE TITLE
Timing out - Oct 17 & 18

### ISSUE THREAD

**Issue by fpurcell** [iandees/xapi-servlet#17]
Hey Ian,

I'm seeing these two requests timeout:

wget http://jxapi.openstreetmap.org/xapi/api/0.6/map?bbox=-123.4,44.8,-121.5,45.8

&

wget http://open.mapquestapi.com/xapi/api/0.6/map?bbox=-121.6,45.7,-121.5,45.8

Things were working fine last week, but as of maybe Saturday Oct 15th, the service has been timing out

--Frank

**Comment by ToeBee** [comment]
It is probably wget that is timing out, not the XAPI since wget has a default timeout of 15 minutes, after which it aborts and retries the request which increases load on the server and slows down the query even more. XAPI response time can vary greatly depending on server load load, data size, etc. so you definitely need to add a --timeout=0 to that wget command to disable its default timeout. I have performed xapi requests on my own server that take over 2 hours to complete. You just have to be patient.
